name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: {{ '${{ matrix.name }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.13'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.13'
            tox_env: 'docs'
            os: 'ubuntu-latest'
{% for env in tox_environments %}
{% set prefix = env.split('-')[0] -%}
{% set freethreaded = prefix.endswith('t') %}
{% if prefix.startswith('pypy') %}
{% set python %}pypy-{{ prefix[4] }}.{{ prefix[5:] }}{% endset %}
{% set cpython %}pp{{ prefix[4:5] }}{% endset %}
{% else %}
{% set python %}{{ prefix[2] }}.{{ prefix[3:].rstrip('t') }}{% endset %}
{% set cpython %}cp{{ prefix[2:] }}{% endset %}
{% endif %}
{% for os, python_arch in [
    ['ubuntu', 'x64'],
    ['windows', 'x64'],
    ['macos', 'arm64'],
] %}
          - name: '{{ env }} ({{ os }}/{{ python_arch }})'
            python: '{{ python }}'
            python_arch: '{{ python_arch }}'
            tox_env: '{{ env }}'
            os: '{{ os }}-latest'
{% if 'cover' in env %}
            cover: true
{% endif %}
{% endfor %}
{% endfor %}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: {{ '${{ matrix.python }}' }}
        architecture: {{ '${{ matrix.python_arch }}' }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      run: >
        tox -e {{ '${{ matrix.tox_env }}' }} -v
    - uses: coverallsapp/github-action@v2
      if: matrix.cover
      continue-on-error: true
      with:
        flag-name: {{ '${{ matrix.name }}' }}
        parallel: true
    - uses: codecov/codecov-action@v5
      if: matrix.cover
      with:
        flags: {{ '${{ matrix.name }}' }}
        token: {{ '${{ secrets.CODECOV_TOKEN }}' }}
        verbose: true
  finish:
    needs: test
    if: {{ '${{ always() }}' }}
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
{{- '' }}
